comments/urls.py
from django.urls import path
from . import views

app_name = 'comments'

urlpatterns = [
    path('create/<int:post_id>/', views.create_comment, name='create_comment'),
    path('update/<int:comment_id>/', views.update_comment, name='update_comment'),
    path('delete/<int:comment_id>/', views.delete_comment, name='delete_comment'),
]

instagram_clone/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('posts.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('profiles/', include('profiles.urls')),
    # path('posts/', include('posts.urls')),
    path('relationships/', include('relationships.urls', namespace='relationships')),
    path('comments/', include('comments.urls', namespace='comments')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('posts/create/', views.create_post, name='create'),
    path('posts/detail/<int:pk>/', views.detail_post, name='detail'),
    path('posts/update/<int:pk>/', views.update_post, name='update'),
    path('posts/delete/<int:pk>/', views.delete_post, name='delete'),
    path('', views.list_posts, name='list'),
    path('posts/like/<int:pk>/', views.like_post, name='like'),
    # path('create_comment/<int:post_id>/', views.create_comment, name='create_comment'),
    # path('update_comment/<int:comment_id>/', views.update_comment, name='update_comment'),
    # path('delete_comment/<int:comment_id>/', views.delete_comment, name='delete_comment'),
    # path('post_feed/', views.post_feed, name='post_feed'),
]

profiles/urls.py
from django.urls import path
from . import views

app_name = 'profiles'

urlpatterns = [
    path('create/', views.create_profile, name='create'),
    path('detail/<int:pk>/', views.detail_profile, name='detail'),
    path('update/<int:pk>/', views.update_profile, name='update'),
    # path('delete/<int:pk>/', views.delete_profile, name='delete'),
    path('other_users/', views.other_users, name='other_users'),
]

comments/models.py
from django.db import models
from django.contrib.auth.models import User
from posts.models import Post


class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    text = models.TextField()
    parent = models.ForeignKey('self', null=True, blank=True, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.user.username}'s comment on {self.post.title}"

comments/forms.py
from django import forms
from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text', 'parent')
        widgets = {
            'text': forms.Textarea(attrs={'rows': 3}),
            'parent': forms.HiddenInput(),
        }

comments/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from posts.models import Post
from .models import Comment
from django.http import HttpResponseForbidden
from .forms import CommentForm


# Create your views here.
@login_required
def create_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.user = request.user
            comment.save()
            return redirect('posts:detail', pk=post.id)
    else:
        form = CommentForm()
    return render(request, 'comments/create_comment.html', {'form': form})


@login_required
def update_comment(request, comment_id):
    comment = get_object_or_404(Comment, id=comment_id)
    if request.user != comment.user:
        return HttpResponseForbidden('You cannot edit this comment.')

    if request.method == 'POST':
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            form.save()
            return redirect('posts:detail', pk=comment.post.id)
    else:
        form = CommentForm(instance=comment)
    return render(request, 'comments/update_comment.html', {'form': form})


@login_required
def delete_comment(request, comment_id):
    comment = get_object_or_404(Comment, id=comment_id)
    if request.user != comment.user and request.user != comment.post.user:
        return HttpResponseForbidden('You cannot delete this comment.')

    if request.method == 'POST':
        post_id = comment.post.id
        comment.delete()
        return redirect('posts:detail', pk=post_id)
    return render(request, 'comments/delete_comment.html', {'comment': comment})

comments/templates/comments/comment_partial.html
{% load my_tags %}
{% load comment_tags %}

{% for comment in comments %}
    <div style="margin-left: {{ level|multiply:30 }}px;">
        <div class="bg-white p-2">
            <div class="d-flex flex-row user-info">
                <img class="rounded-circle" src="{{comment.user.profile.profile_picture.url}}" width="30" height="30">
                <a href="{% url 'profiles:detail' comment.user.pk %}" style="text-decoration: none;">
                    <div class="d-flex flex-column justify-content-start ms-2 ">
                        <span class="d-block font-weight-bold name" style="text-transform: capitalize;">{{comment.user.username}} {{comment.user.profile.last_name}}</span>
                        <span class="date text-black-50">{{comment.created_at}}</span>
                    </div>
                </a>
            </div>
            <div class="mt-2">
                <span class="comment-text fw-bold text-decoration-underline" style="font-size: medium;">{{ comment.text }}</span>
                <a href="{% url 'comments:update_comment' comment_id=comment.id %}" class="text-decoration-none ms-2" style="font-size:12px">Edit</a>
                <a href="{% url 'comments:delete_comment' comment_id=comment.id %}" class="text-decoration-none" style="font-size:12px">Delete</a>
            </div>
        </div>
        <form method="post" class="p-2" action="{% url 'comments:create_comment' post_id=comment.post.id %}" style="display:flex; column-gap:8px">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="hidden" name="parent" value="{{ comment.id }}">
            <button type="submit" class="rounded" style="font-size:12px; padding:0 5px">Reply</button>
            <textarea name="text" class="rounded" cols="10" rows="1" required id="id_text"></textarea>
            
        </form>

        {% if comment.comment_set.all %}
            {% render_nested_comments comment.comment_set.all level=level|add:1 %}
        {% endif %}
    </div>
{% endfor %}

comments/templates/comments/create_comment.html
{% extends 'accounts/base.html' %}

{% block content %}
<h2>Create a Comment</h2>
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Create Comment</button>
</form>
{% endblock %}

comments/templates/comments/delete_comment copy.html
{% extends 'accounts/base.html' %}

{% block content %}
<h2>Delete Comment</h2>
<p>Are you sure you want to delete this comment?</p>
<form method="post">
  {% csrf_token %}
  <button type="submit">Yes, Delete Comment</button>
  <a href="{% url 'posts:detail' pk=comment.post.id %}">Cancel</a>
</form>
{% endblock %}

comments/templates/comments/delete_comment.html
{% extends 'accounts/base.html' %}
{% load static %}
{% block content %}

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <script src="https://kit.fontawesome.com/fc1e235b2e.js"></script>
  <link rel="stylesheet" href="{% static 'assets2/style.css' %}">
  <title>Instagram Login Form</title>
</head>

<body>
  <div id="wrapper">
    <div class="container">
      <div class="phone-app-ddemo"></div>
      <div class="form-data">
        <form action="" method="POST" enctype="multipart/form-data">
			{% csrf_token %}
          <div class="logo">
            <h3 class="display-5" style="padding: 20px;">Delete Comment</h3>
          </div>
            <p>Are you sure you want to delete this comment?</p>
            <h3 class="fs-3 border border-rounded">{{ comment.text }}</h3>
            <button class="btn btn-danger mt-4 fs-5" type="submit">Yes, Delete Comment</button>
            <a class="mt-4" href="{% url 'posts:detail' pk=comment.post.id %}">Cancel</a>
        </form>
      </div>
    </div>
    {% include 'partials/_footer.html' %}
  </div>
</body>
{% endblock content %}

comments/templates/comments/update_comment copy.html
{% extends 'accounts/base.html' %}

{% block content %}
<h2>Update Comment</h2>
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Update Comment</button>
</form>
{% endblock %}

comments/templates/comments/update_comment.html
{% extends 'accounts/base.html' %}
{% load static %}
{% block content %}

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <script src="https://kit.fontawesome.com/fc1e235b2e.js"></script>
  <link rel="stylesheet" href="{% static 'assets2/style.css' %}">
  <title>Instagram Login Form</title>
</head>

<body>
  <div id="wrapper">
    <div class="container">
      <div class="phone-app-ddemo"></div>
      <div class="form-data">
        <form action="" method="POST" enctype="multipart/form-data">
			{% csrf_token %}
          <div class="logo">
            <h3 style="padding: 20px; font-size: 20px;">Edit Comment</h3>
          </div>
          {{form.text.label_tag}} <br>
          {{form.text}} <br>
          <button class="form-btn" type="submit">Update Comment</button>
        </form>
      </div>
    </div>
    {% include 'partials/_footer.html' %}
  </div>
</body>
{% endblock content %}