instagram_clone/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('posts.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('profiles/', include('profiles.urls')),
    # path('posts/', include('posts.urls')),
    path('relationships/', include('relationships.urls', namespace='relationships')),
    path('comments/', include('comments.urls', namespace='comments')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('posts/create/', views.create_post, name='create'),
    path('posts/detail/<int:pk>/', views.detail_post, name='detail'),
    path('posts/update/<int:pk>/', views.update_post, name='update'),
    path('posts/delete/<int:pk>/', views.delete_post, name='delete'),
    path('', views.list_posts, name='list'),
    path('posts/like/<int:pk>/', views.like_post, name='like'),
    # path('create_comment/<int:post_id>/', views.create_comment, name='create_comment'),
    # path('update_comment/<int:comment_id>/', views.update_comment, name='update_comment'),
    # path('delete_comment/<int:comment_id>/', views.delete_comment, name='delete_comment'),
    # path('post_feed/', views.post_feed, name='post_feed'),
]

profiles/urls.py
from django.urls import path
from . import views

app_name = 'profiles'

urlpatterns = [
    path('create/', views.create_profile, name='create'),
    path('detail/<int:pk>/', views.detail_profile, name='detail'),
    path('update/<int:pk>/', views.update_profile, name='update'),
    # path('delete/<int:pk>/', views.delete_profile, name='delete'),
    path('other_users/', views.other_users, name='other_users'),
]

relationships/urls.py
# relationships/urls.py

from django.urls import path
from . import views

app_name = 'relationships'

urlpatterns = [
    path('follow/<int:pk>/', views.follow, name='follow'),
    path('unfollow/<int:pk>/', views.unfollow, name='unfollow'),
]

profiles/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.core.files.storage import default_storage
from django.dispatch import receiver


# class Profile(models.Model):
#     user = models.OneToOneField(User, on_delete=models.CASCADE)
#     bio = models.TextField(blank=True)
#     profile_picture = models.ImageField(upload_to='profile_pictures/', default='default.png')

#     def __str__(self):
#         return self.user.username


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    firstname = models.CharField(max_length=30, blank=True)
    lastname = models.CharField(max_length=30, blank=True)
    bio = models.TextField(blank=True, null=True)
    profile_picture = models.ImageField(upload_to='profile_pictures/', default='default.jpg')

    def save(self, *args, **kwargs):
        if self.pk:
            old_profile = Profile.objects.get(pk=self.pk)
            if old_profile.profile_picture and self.profile_picture != old_profile.profile_picture:
                default_storage.delete(old_profile.profile_picture.path)

        super(Profile, self).save(*args, **kwargs)

    def __str__(self):
        return self.user.username

profiles/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Profile


class ProfileForm(forms.ModelForm):
    first_name = forms.CharField(max_length=30, required=True, label='First name')
    last_name = forms.CharField(max_length=30, required=True, label='Last name')

    class Meta:
        model = Profile
        fields = ('bio', 'profile_picture', 'first_name', 'last_name')

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super(ProfileForm, self).__init__(*args, **kwargs)
        if user:
            self.fields['first_name'].initial = user.first_name
            self.fields['last_name'].initial = user.last_name


# class UserForm(forms.ModelForm):
#     class Meta:
#         model = User
#         fields = ('first_name', 'last_name')

profiles/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
# from django.http import HttpResponseForbidden
# from django.http import HttpResponseRedirect
from .models import Profile
from .forms import ProfileForm
from posts.models import Post
from relationships.models import Relationship
from django.db.models import Count


@login_required
def create_profile(request):
    if hasattr(request.user, 'profile'):
        return redirect('profiles:detail', request.user.profile.pk)

    if request.method == 'POST':
        form = ProfileForm(request.POST, request.FILES)
        if form.is_valid():
            profile = form.save(commit=False)
            profile.user = request.user
            profile.save()

            request.user.first_name = form.cleaned_data['first_name']
            request.user.last_name = form.cleaned_data['last_name']
            request.user.save()

            return redirect('profiles:detail', profile.pk)
    else:
        form = ProfileForm()
    return render(request, 'profiles/create.html', {'form': form})


@login_required
def detail_profile(request, pk):
    profile = get_object_or_404(Profile, pk=pk)
    posts = Post.objects.filter(user=profile.user).annotate(comment_count=Count('comment')).order_by('-created_at')
    following_count = Relationship.objects.filter(follower=profile.user).count()
    followers_count = Relationship.objects.filter(following=profile.user).count()
    posts_count = len(posts)
    context = {
        'profile': profile,
        'posts': posts,
        'following_count': following_count,
        'followers_count': followers_count,
        'posts_count': posts_count,
    }
    return render(request, 'profiles/detail.html', context)


# @login_required
# def update_profile(request, pk):
#     profile = get_object_or_404(Profile, pk=pk)
#     next_page = request.GET.get('next', '/')

#     if request.user != profile.user:
#         return HttpResponseRedirect(next_page)

#     if request.method == 'POST':
#         form = ProfileForm(request.POST, request.FILES, instance=profile)
#         if form.is_valid():
#             form.save()
#             return redirect('profiles:detail', pk)
#     else:
#         form = ProfileForm(instance=profile)
#     return render(request, 'profiles/update.html', {'form': form})


@login_required
def update_profile(request, pk):
    profile = get_object_or_404(Profile, pk=pk)

    if request.method == 'POST':
        form = ProfileForm(request.POST, request.FILES, instance=profile, user=request.user)
        if form.is_valid():
            form.save()

            request.user.first_name = form.cleaned_data['first_name']
            request.user.last_name = form.cleaned_data['last_name']
            request.user.save()
            return redirect('profiles:detail', pk)
    else:
        form = ProfileForm(instance=profile, user=request.user)
    return render(request, 'profiles/update.html', {'form': form})


# @login_required
# def delete_profile(request, pk):
#     profile = get_object_or_404(Profile, pk=pk)
#     if request.method == 'POST':
#         profile.delete()
#         return redirect('accounts:welcome')
#     return render(request, 'profiles/delete.html', {'profile': profile})


@login_required
def other_users(request):
    users = User.objects.exclude(pk=request.user.pk)  # Excluding the current user
    context = {
        'users': users,
    }
    return render(request, 'profiles/other_users.html', context)

profiles/templates/profiles/create copy.html
{% extends 'accounts/base.html' %}

{% block content %}
  <h2>Create Profile</h2>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.first_name.label_tag }}<br>
    {{ form.first_name }}<br>
    {{ form.last_name.label_tag }}<br>
    {{ form.last_name }}<br>
    {{ form.bio.label_tag }}<br>
    {{ form.bio }}<br>
    {{ form.profile_picture.label_tag }}<br>
    {{ form.profile_picture }}<br>
    <button type="submit">Create</button>
  </form>
{% endblock %}

profiles/templates/profiles/create.html
{% extends 'accounts/base.html' %}
{% load static %}
{% block content %}
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <script src="https://kit.fontawesome.com/fc1e235b2e.js"></script>
  <link rel="stylesheet" href="{% static 'assets2/style.css' %}">
  <title>Instagram Edit Form</title>
</head>

<body>
  <div id="wrapper">
    <div class="container">
      <div class="phone-app-ddemo"></div>
      <div class="form-data">
        <form action="" method="POST" enctype="multipart/form-data">
			    {% csrf_token %}
          <div class="logo">
            <h3 class="display-5" style="padding: 20px;">Create Profile</h3>
          </div>
          {{ form.first_name.label_tag }}<br>
          {{ form.first_name }}<br>
          {{ form.last_name.label_tag }}<br>
          {{ form.last_name }}<br>
          {{ form.bio.label_tag }}<br>
          {{ form.bio }}<br>
          {{ form.profile_picture.label_tag }}<br>
          {{ form.profile_picture }}<br>
          <button class="form-btn" type="submit">Create</button>
        </form>
      </div>
    </div>
    {% include 'partials/_footer.html' %}
  </div>
</body>
{% endblock content %}

profiles/templates/profiles/delete.html
{% extends 'accounts/base.html' %}

{% block content %}
  <h2>Are you sure you want to delete your profile?</h2>
  <form method="post">
    {% csrf_token %}
    <button type="submit">Yes, delete my profile</button>
  </form>
{% endblock %}

profiles/templates/profiles/detail copy.html
{% extends 'accounts/base.html' %}

{% load relationship_tags %}

{% block content %}
  <h2>{{ profile.user.username }}'s Profile</h2>
    <!-- Add first_name and last_name here -->
    {% if profile.user.first_name %}
    <p>First Name: {{ profile.user.first_name }}</p>
    {% endif %}
    {% if profile.user.last_name %}
    <p>Last Name: {{ profile.user.last_name }}</p>
    {% endif %}
    <!-- <p>First Name: {{ profile.user.first_name }}</p>
    <p>Last Name: {{ profile.user.last_name }}</p> -->
    <!-- Add this after the profile details -->
    {% if request.user != profile.user %}
    {% if request.user|is_following:profile.user %}
        <a href="{% url 'relationships:unfollow' profile.user.pk %}">Unfollow</a>
    {% else %}
        <a href="{% url 'relationships:follow' profile.user.pk %}">Follow</a>
    {% endif %}
    {% endif %}

  <p>{{ profile.bio }}</p>
  {% if profile.profile_picture %}
  <img src="{{ profile.profile_picture.url }}" alt="{{ profile.user.username }}'s profile picture" width="200">
  {% endif %}
  <br>
  {% if request.user == profile.user %}
    <a href="{% url 'profiles:update' profile.pk %}">Edit Profile</a>
    <br>
    <!-- <a href="{% url 'posts:create' %}">Create Post</a> -->
  {% endif %}
  <h3>{{ profile.user.username }}'s Posts</h3>
  {% for post in posts %}
    <a href="{% url 'posts:detail' post.pk %}">
      <img src="{{ post.image.url }}" alt="{{ post.user.username }}'s post image" width="150">
    </a>
  {% empty %}
    <p>No posts yet.</p>
  {% endfor %}
{% endblock %}

profiles/templates/profiles/detail.html
{% extends 'accounts/base.html' %}
{% load static %}
{% load relationship_tags %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Metadata -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="author" content="George W. Park">
    <meta name="description" content="This project demonstrates how CSS grid (with flexbox and float fallback) can be used to re-create the layout of an Instagram profile page.">
    <!-- Title -->
    <title>Instagram Profile Layout</title>
    <!-- External CSS Files -->
    <link rel="stylesheet" href="{% static 'assets3/css/reset.css' %}">
    <link rel="stylesheet" href="{% static 'assets3/css/styles.css' %}">
    <link rel="stylesheet" href="{% static 'css/opensans.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css">
    <!-- <link rel="stylesheet" href="{% static 'css/fontawesome.css' %}"> -->
  </head>
  <body>
    <header>
        <br><br><br>
        <div class="container">
          <div class="profile">
              <div class="profile-image">
                <img src="{{profile.profile_picture.url}}" alt="" style="width: 200px; height: 200px;">
              </div>
              <div class="profile-user-settings">
                {% if profile.user.first_name %}
                <h6 class="profile-user-name mb-4">{{profile.user.first_name}} {{profile.user.last_name}}</h6>
                <br>
                {% endif %}
                <h5 style="font-size: 15px;" class="profile-user-name">@{{profile.user.username}}</h5>
                {% if request.user.is_authenticated and request.user == profile.user %}
                <a style="text-decoration: none;" href="{% url 'profiles:update' profile.user.pk %}" class="btn profile-edit-btn">Edit Profile</a>
                <a style="text-decoration: none;" href="{% url 'logout' %}" class="btn profile-edit-btn">Logout</a>
                <button class="btn profile-settings-btn" aria-label="profile settings"><i class="fas fa-cog" aria-hidden="true"></i></button>
                {% endif %}
                <br><br>
                {% if request.user != profile.user %}
                {% if request.user|is_following:profile.user %}
                  <a href="{% url 'relationships:unfollow' profile.user.pk %}" class="btn profile-edit-btn" style="color: red;">Unfollow</a> <br><br>
                {% else %}
                  <a href="{% url 'relationships:follow' profile.user.pk %}" class="btn profile-edit-btn" style="color: green;">Follow</a> <br><br>
                {% endif %}
                {% endif %}
                {% if request.user.is_authenticated and request.user != profile.user %}
                <a href="#" class="btn profile-edit-btn">Message</a> <br><br>
                {% endif %}
                <br>
              </div>
              <div class="profile-bio">
                <br>
                {% if profile.bio %}
                <p><span class="profile-real-name"></span>◉ {{profile.bio}}</p>
                {% endif %}
                {% if profile.location %}
                <p><span class="profile-real-name"></span>◉ {{profile.location}}</p>
                {% endif %}
                {% if profile.url %}
                <p><span class="profile-real-name"></span>◉ <a href="{{profile.url}}">{{profile.url}}</a></p>
                {% endif %}
                <br><br>
                <div class="profile-user-settings">
                    <a  href="{% url 'profiles:detail' profile.user.pk %}"  class="btns profiele-edit-btn">Posts</a>
                    {% if request.user == profile.user %}
                    <a  href="#"  class="btns profeile-edit-btn">Saved</a>
                    {% endif %}
                </div>
              </div>
              <div class="profile-stats">
                <ul>
                    <li><span class="profile-stat-count">{{posts_count}}</span> posts</li>
                    <li><span class="profile-stat-count">{{followers_count}}</span> followers</li>
                    <li><span class="profile-stat-count">{{following_count}}</span> following</li>
                </ul>
                <br>
              </div>
          </div>
          <!-- End of profile section -->
        </div>
        <!-- End of container -->
      </header>
    <main>
        <div class="container">
          <div class="gallery">
              {% for post in posts %}
              <a href="{% url 'posts:detail' post.pk %}">
                <div class="gallery-item" tabindex="0">
                    <img src="{{ post.image.url }}" class="gallery-image" alt="" style="width: 500px; height: 300px; object-fit: cover;">
                    <div class="gallery-item-info">
                      <ul>
                          <li class="gallery-item-likes"><span class="visually-hidden">Likes:</span><i class="fas fa-heart" aria-hidden="true"></i> {{post.likes.count}}</li>
                          <li class="gallery-item-comments"><span class="visually-hidden">Comments:</span><i class="fas fa-comment" aria-hidden="true"></i> {{post.comment_count}}</li>
                      </ul>
                    </div>
                </div>
              </a>
              {% endfor %}
          </div>
          <!-- End of gallery -->
        </div>
        <!-- End of container -->
    </main>
    {% endblock content %}
  </body>
</html>

profiles/templates/profiles/other_users copy.html
{% extends "accounts/base.html" %}
{% load relationship_tags %}

{% block content %}
    <h1>Other Users</h1>
    <ul>
        {% for user in users %}
            {% if not user.is_superuser %}
                <li>
                    <a href="{% url 'profiles:detail' user.pk %}">{{ user.username }}</a> - 
                    {% if request.user|is_following:user %}
                        <a href="{% url 'relationships:unfollow' user.pk %}">Unfollow</a>
                    {% else %}
                        <a href="{% url 'relationships:follow' user.pk %}">Follow</a>
                    {% endif %}
                </li>

            {% endif %}
        {% empty %}
            <li>No other users available.</li>
        {% endfor %}
    </ul>
{% endblock %}

profiles/templates/profiles/other_users.html
{% extends "accounts/base.html" %}
{% load relationship_tags %}

{% block content %}
<div style="text-align:center">
    <h1>Other Users</h1>
    <ul>
        {% for user in users %}
            {% if not user.is_superuser %}
                <li>
                    <a href="{% url 'profiles:detail' user.pk %}">{{ user.username }}</a> - 
                    {% if request.user|is_following:user %}
                        <a href="{% url 'relationships:unfollow' user.pk %}">Unfollow</a>
                    {% else %}
                        <a href="{% url 'relationships:follow' user.pk %}">Follow</a>
                    {% endif %}
                </li>

            {% endif %}
        {% empty %}
            <li>No other users available.</li>
        {% endfor %}
    </ul>
</div>
{% endblock %}

profiles/templates/profiles/update copy.html
{% extends 'accounts/base.html' %}

{% block content %}
  <h2>Edit Profile</h2>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Update</button>
  </form>
{% endblock %}

profiles/templates/profiles/update.html
{% extends 'accounts/base.html' %}
{% load static %}
{% block content %}
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <script src="https://kit.fontawesome.com/fc1e235b2e.js"></script>
  <link rel="stylesheet" href="{% static 'assets2/style.css' %}">
  <title>Instagram Edit Form</title>
</head>

<body>
  <div id="wrapper">
    <div class="container">
      <div class="phone-app-ddemo"></div>
      <div class="form-data">
        <form action="" method="POST" enctype="multipart/form-data">
			    {% csrf_token %}
          <div class="logo">
            <h3 class="display-5" style="padding: 20px;">Edit Profile</h3>
          </div>
          {{form.profile_picture}} <br>
          {{form.first_name}} <br>
          {{form.last_name}} <br>
          {{form.bio}} <br>
          <button class="form-btn" type="submit">Update</button>
        </form>
      </div>
    </div>
    {% include 'partials/_footer.html' %}
  </div>
</body>
{% endblock content %}