accounts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.user_login, name='login'),
    path('welcome/', views.welcome, name='welcome'),
    path('logout/', views.user_logout, name='logout'),
]

instagram_clone/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('posts.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('profiles/', include('profiles.urls')),
    # path('posts/', include('posts.urls')),
    path('relationships/', include('relationships.urls', namespace='relationships')),
    path('comments/', include('comments.urls', namespace='comments')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('posts/create/', views.create_post, name='create'),
    path('posts/detail/<int:pk>/', views.detail_post, name='detail'),
    path('posts/update/<int:pk>/', views.update_post, name='update'),
    path('posts/delete/<int:pk>/', views.delete_post, name='delete'),
    path('', views.list_posts, name='list'),
    path('posts/like/<int:pk>/', views.like_post, name='like'),
    # path('create_comment/<int:post_id>/', views.create_comment, name='create_comment'),
    # path('update_comment/<int:comment_id>/', views.update_comment, name='update_comment'),
    # path('delete_comment/<int:comment_id>/', views.delete_comment, name='delete_comment'),
    # path('post_feed/', views.post_feed, name='post_feed'),
]

profiles/urls.py
from django.urls import path
from . import views

app_name = 'profiles'

urlpatterns = [
    path('create/', views.create_profile, name='create'),
    path('detail/<int:pk>/', views.detail_profile, name='detail'),
    path('update/<int:pk>/', views.update_profile, name='update'),
    # path('delete/<int:pk>/', views.delete_profile, name='delete'),
    path('other_users/', views.other_users, name='other_users'),
]

accounts/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User


class SignUpForm(UserCreationForm):
    email = forms.EmailField(max_length=254, required=True, widget=forms.EmailInput(attrs={'placeholder': 'Email'}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Password'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Confirm Password'}))

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')
        widgets = {
            'username': forms.TextInput(attrs={'placeholder': 'Username'}),
        }


class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Username'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Password'}))
    pass

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from .forms import SignUpForm, LoginForm
from relationships.models import Relationship
from posts.models import Post
from django.contrib.auth.models import User


def signup(request):
    if request.user.is_authenticated:
        return redirect('welcome')

    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('profiles:create')
    else:
        form = SignUpForm()
    return render(request, 'accounts/signup.html', {'form': form})


def user_login(request):
    if request.user.is_authenticated:
        return redirect('welcome')

    if request.method == 'POST':
        form = LoginForm(request, request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('welcome')
    else:
        form = LoginForm()
    return render(request, 'accounts/login.html', {'form': form})


def user_logout(request):
    logout(request)
    return redirect('login')


@login_required
def welcome(request):
    # following_users = Relationship.objects.filter(follower=request.user).values_list('following')
    # posts = Post.objects.filter(user__in=following_users).order_by('-created_at')
    following_users = Relationship.objects.filter(follower=request.user).values_list('following')
    posts = Post.objects.filter(user__in=following_users).order_by('-created_at')
    users = User.objects.all()
    context = {
        'posts': posts,
        'users': users,
    }

    return render(request, 'accounts/welcome.html', context)

accounts/templates/accounts/base copy.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Instagram Clone{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
    <nav>
        {% if request.user.is_authenticated %}
            {% if request.user.profile %}
                <a href="{% url 'profiles:detail' request.user.profile.pk %}">My Profile</a> |
            {% endif %}
            <a href="{% url 'welcome' %}">Welcome</a> |
            <a href="{% url 'profiles:other_users' %}">Explore Users</a> |
            <a href="{% url 'posts:create' %}">Create Post</a> |
            <a href="{% url 'logout' %}">Logout</a>
        {% else %}
            <a href="{% url 'login' %}">Login</a> |
            <a href="{% url 'signup' %}">Sign Up</a>
        {% endif %}
    </nav>

    <main>
        {% block content %}
        {% endblock %}
        <br>
        <!-- Back link to go to last visited page -->
        {% with request.META.HTTP_REFERER as referer %}
            {% if referer %}
                <a href="{{ referer }}">Go Back</a>
            {% endif %}
        {% endwith %}
    </main>
    
</body>
</html>

accounts/templates/accounts/login.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <script src="https://kit.fontawesome.com/fc1e235b2e.js"></script>
    <link rel="stylesheet" href="{% static 'assets2/style.css' %}" />
    <title>Instagram | Login</title>
  </head>

  <body>
    <div id="wrapper">
      <div class="container">
        <div class="phone-app-demo"></div>
        <div class="form-data li-none">
          <form action="" method="POST">
            {% csrf_token %}
            <div class="logo">
              <img src="{% static 'assets2/images/logo.png' %}" alt="logo" />
            </div>
            <!-- <input type="text" placeholder="Phone number, username, or email"> -->
            <!-- <input type="password" placeholder="Password"> -->
            {{ form }}
            <button class="form-btn" type="submit">Log in</button>
            <!-- <a href="index.html" class="form-btn" type="submit">Log in</a> -->
            <span class="has-separator">Or</span>
            <a class="facebook-login" href="#">
              <i class="fab fa-facebook-square"></i> Log in with Facebook
            </a>
            <a class="password-reset" href="#">Forgot password?</a>
          </form>
          <div class="sign-up">
            Don't have an account? <a href="{% url 'signup' %}">Sign up</a>
          </div>
          <div class="get-the-app">
            <span>Get the app.</span>
            <div class="badges">
              <img
                src="{% static 'assets2/images/app-store.png' %}"
                alt="app-store badge"
              />
              <img
                src="{% static 'assets2/images/google-play.png' %}"
                alt="google-play badge"
              />
            </div>
          </div>
        </div>
      </div>
      {% include 'partials/_footer.html' %}
    </div>
  </body>
</html>

accounts/templates/accounts/signup.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <script src="https://kit.fontawesome.com/fc1e235b2e.js"></script>
    <link rel="stylesheet" href="{% static 'assets2/style.css' %}" />
    <title>Instagram | Register</title>
  </head>

  <body>
    <div id="wrapper">
      <div class="container">
        <div class="phone-app-demo"></div>
        <div class="form-data li-none">
          <form action="" method="POST">
            {% csrf_token %}
            <div class="logo">
              <img src="{% static 'assets2/images/logo.png' %}" alt="logo" />
            </div>
            <!-- <input type="text" placeholder="Phone number, username, or email"> -->
            <!-- <input type="password" placeholder="Password"> -->
            <!-- {{ form.username.label_tag }} -->
            {{ form.username }}
            {{ form.username.errors }}
            <br>
            <!-- {{ form.email.label_tag }} -->
            {{ form.email }}
            {{ form.email.errors }}
            <br>
            <!-- {{ form.password1.label_tag }} -->
            {{ form.password1 }}
            {{ form.password1.errors }}
            <br>
            <!-- {{ form.password2.label_tag }} -->
            {{ form.password2 }}
            {{ form.password2.errors }}
            <br>
            <button class="form-btn" type="submit">Sign up</button>
            <!-- <a href="index.html" class="form-btn" type="submit">Log in</a> -->
            <span class="has-separator">Or</span>
            <a class="facebook-login" href="#">
              <i class="fab fa-facebook-square"></i> Log in with Facebook
            </a>
            <a class="password-reset" href="#">Forgot password?</a>
          </form>
          <div class="sign-up">
            Already have an account? <a href="{% url 'login' %}">Log in</a>
          </div>
          <div class="get-the-app">
            <span>Get the app.</span>
            <div class="badges">
              <img
                src="{% static 'assets2/images/app-store.png' %}"
                alt="app-store badge"
              />
              <img
                src="{% static 'assets2/images/google-play.png' %}"
                alt="google-play badge"
              />
            </div>
          </div>
        </div>
      </div>
      {% include 'partials/_footer.html' %}
    </div>
  </body>
</html>

accounts/templates/accounts/welcome copy.html
{% extends 'accounts/base.html' %}

{% block content %}
<h2>Welcome, {{ request.user.username }}!</h2>
<p><a href="{% url 'profiles:other_users' %}">Explore other users</a></p>

<h3>Posts from people you follow:</h3>

{% for post in posts %}
    <div>
        <h4>{{ post.user.username }}</h4>
        <p>{{ post.caption }}</p>
        <a href="{% url 'posts:detail' post.id %}">
            <img src="{{ post.image.url }}" alt="{{ post.caption }}" width="200">
        </a>
        <p>Likes: {{ post.likes.count }}</p>
    </div>
{% empty %}
    <p>You don't have any posts from people you follow yet.</p>
{% endfor %}
{% endblock %}