comments/urls.py
from django.urls import path
from . import views

app_name = 'comments'

urlpatterns = [
    path('create/<int:post_id>/', views.create_comment, name='create_comment'),
    path('update/<int:comment_id>/', views.update_comment, name='update_comment'),
    path('delete/<int:comment_id>/', views.delete_comment, name='delete_comment'),
]

instagram_clone/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('posts.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('profiles/', include('profiles.urls')),
    # path('posts/', include('posts.urls')),
    path('relationships/', include('relationships.urls', namespace='relationships')),
    path('comments/', include('comments.urls', namespace='comments')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('posts/create/', views.create_post, name='create'),
    path('posts/detail/<int:pk>/', views.detail_post, name='detail'),
    path('posts/update/<int:pk>/', views.update_post, name='update'),
    path('posts/delete/<int:pk>/', views.delete_post, name='delete'),
    path('', views.list_posts, name='list'),
    path('posts/like/<int:pk>/', views.like_post, name='like'),
    # path('create_comment/<int:post_id>/', views.create_comment, name='create_comment'),
    # path('update_comment/<int:comment_id>/', views.update_comment, name='update_comment'),
    # path('delete_comment/<int:comment_id>/', views.delete_comment, name='delete_comment'),
    # path('post_feed/', views.post_feed, name='post_feed'),
]

profiles/urls.py
from django.urls import path
from . import views

app_name = 'profiles'

urlpatterns = [
    path('create/', views.create_profile, name='create'),
    path('detail/<int:pk>/', views.detail_profile, name='detail'),
    path('update/<int:pk>/', views.update_profile, name='update'),
    # path('delete/<int:pk>/', views.delete_profile, name='delete'),
    path('other_users/', views.other_users, name='other_users'),
]

comments/models.py
from django.db import models
from django.contrib.auth.models import User
from posts.models import Post


class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    text = models.TextField()
    parent = models.ForeignKey('self', null=True, blank=True, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.user.username}'s comment on {self.post.title}"

posts/models.py
from django.db import models
from django.contrib.auth.models import User


class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    likes = models.ManyToManyField(User, related_name='liked_posts', blank=True)
    image = models.ImageField(upload_to='post_images/')
    caption = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.user.username}\'s post'


# class Comment(models.Model):
#     user = models.ForeignKey(User, on_delete=models.CASCADE)
#     post = models.ForeignKey(Post, on_delete=models.CASCADE)
#     text = models.TextField()
#     parent = models.ForeignKey('self', null=True, blank=True, on_delete=models.CASCADE)
#     created_at = models.DateTimeField(auto_now_add=True)
#     updated_at = models.DateTimeField(auto_now=True)

#     def __str__(self):
#         return f"{self.user.username}'s comment on {self.post.title}"

posts/forms.py
from django import forms
from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['image', 'caption']


# class CommentForm(forms.ModelForm):
#     class Meta:
#         model = Comment
#         fields = ('text', 'parent')
#         widgets = {
#             'text': forms.Textarea(attrs={'rows': 3}),
#             'parent': forms.HiddenInput(),
#         }

posts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from .models import Post
from relationships.models import Relationship
from .forms import PostForm
from .utils import delete_old_image
from django.contrib.auth.models import User
from comments.models import Comment

from django.http import HttpResponseRedirect
from django.urls import reverse
from django.http import HttpResponseForbidden

# from django.db.models import Q
# from django.core.paginator import Paginator
# from relationships.models import Relationship
# from django.contrib.auth.models import User


# @login_required
# def post_feed(request):
#     user = request.user
#     following_users = Relationship.objects.filter(follower=user).values_list('following', flat=True)
    
#     post_items = Post.objects.filter(user__in=following_users).order_by('-created_at')

#     # Pagination
#     paginator = Paginator(post_items, 6)
#     page_number = request.GET.get('page')
#     post_items_paginator = paginator.get_page(page_number)
    
#     # Search users
#     query = request.GET.get('q')
#     users_paginator = None  # Initialize users_paginator as None
#     if query:
#         users = User.objects.filter(Q(username__icontains=query))

#         paginator = Paginator(users, 6)
#         page_number = request.GET.get('page')
#         users_paginator = paginator.get_page(page_number)

#     context = {
#         'post_items': post_items_paginator,
#         'users_paginator': users_paginator,
#     }
#     return render(request, 'posts/post_feed.html', context)


@login_required
def create_post(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.save()
            return redirect('posts:detail', post.pk)
    else:
        form = PostForm()
    return render(request, 'posts/create.html', {'form': form})


@login_required
def detail_post(request, pk):
    post = get_object_or_404(Post, pk=pk)
    comments = Comment.objects.filter(post=post).order_by('-created_at')
    return render(request, 'posts/detail.html', {'post': post, 'comments': comments})


@login_required
def update_post(request, pk):
    post = get_object_or_404(Post, pk=pk)

    if request.user != post.user:
        return redirect('posts:detail', pk)

    if request.method == 'POST':
        old_image_path = post.image.path
        form = PostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            if 'image' in request.FILES:
                delete_old_image(old_image_path)
            form.save()
            return redirect('posts:detail', pk=post.pk)
    else:
        form = PostForm(instance=post)
    return render(request, 'posts/update.html', {'form': form})


@login_required
def delete_post(request, pk):
    post = get_object_or_404(Post, pk=pk)

    if request.user != post.user:
        return redirect('posts:detail', pk)

    if request.method == 'POST':
        old_image_path = post.image.path
        post.delete()
        delete_old_image(old_image_path)
        return redirect('posts:list')

    return render(request, 'posts/confirm_delete.html', {'post': post})


@login_required
def list_posts(request):
    following_users = Relationship.objects.filter(follower=request.user).values_list('following')
    posts = Post.objects.filter(user__in=following_users).order_by('-created_at')
    users = User.objects.all()
    return render(request, 'posts/list.html', {'posts': posts, 'users': users})


@login_required
def like_post(request, pk):
    post = get_object_or_404(Post, pk=pk)

    if request.user.is_authenticated:
        if request.user in post.likes.all():
            post.likes.remove(request.user)
        else:
            post.likes.add(request.user)

    return HttpResponseRedirect(reverse('posts:detail', args=[pk]))


# Create your views here.
# def create_comment(request, post_id):
#     post = get_object_or_404(Post, id=post_id)
#     if request.method == 'POST':
#         form = CommentForm(request.POST)
#         if form.is_valid():
#             comment = form.save(commit=False)
#             comment.post = post
#             comment.user = request.user
#             comment.save()
#             return redirect('posts:detail', pk=post.id)
#     else:
#         form = CommentForm()
#     return render(request, 'posts/create_comment.html', {'form': form})


# def update_comment(request, comment_id):
#     comment = get_object_or_404(Comment, id=comment_id)
#     if request.user != comment.user:
#         return HttpResponseForbidden('You cannot edit this comment.')

#     if request.method == 'POST':
#         form = CommentForm(request.POST, instance=comment)
#         if form.is_valid():
#             form.save()
#             return redirect('posts:detail', pk=comment.post.id)
#     else:
#         form = CommentForm(instance=comment)
#     return render(request, 'posts/update_comment.html', {'form': form})


# def delete_comment(request, comment_id):
#     comment = get_object_or_404(Comment, id=comment_id)
#     if request.user != comment.user and request.user != comment.post.user:
#         return HttpResponseForbidden('You cannot delete this comment.')

#     if request.method == 'POST':
#         post_id = comment.post.id
#         comment.delete()
#         return redirect('posts:detail', pk=post_id)
#     return render(request, 'posts/delete_comment.html', {'comment': comment})

posts/templates/posts/confirm_delete copy.html
{% extends 'accounts/base.html' %}

{% block content %}
    <h2>Confirm Deletion</h2>
    <p>Are you sure you want to delete this post?</p>
    <img src="{{ post.image.url }}" alt="{{ post.user.username }}'s post image" width="300">
    <form method="post">
        {% csrf_token %}
        <button type="submit">Yes, delete this post</button>
    </form>
    <a href="{% url 'posts:detail' post.pk %}">Cancel</a>
{% endblock %}

posts/templates/posts/confirm_delete.html
{% extends 'accounts/base.html' %}
{% load static %}
{% block content %}

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <script src="https://kit.fontawesome.com/fc1e235b2e.js"></script>
  <link rel="stylesheet" href="{% static 'assets2/style.css' %}">
  <title>Instagram Login Form</title>
</head>

<body>
  <div id="wrapper">
    <div class="container">
      <div class="phone-app-ddemo"></div>
      <div class="form-data">
        <form action="" method="POST" enctype="multipart/form-data">
			{% csrf_token %}
          <div class="logo">
            <h3 class="display-5" style="padding: 20px;">Confirm Deletion</h3>
          </div>
            <p>Are you sure you want to delete this post?</p>
            <img src="{{ post.image.url }}" alt="{{ post.user.username }}'s post image" width="300">
            <button class="btn btn-danger mt-4 fs-5" type="submit">Yes, delete this post</button>
            <a class="mt-4" href="{% url 'posts:detail' post.pk %}">Cancel</a>
        </form>
      </div>
    </div>
    {% include 'partials/_footer.html' %}
  </div>
</body>
{% endblock content %}

posts/templates/posts/create copy.html
{% extends 'accounts/base.html' %}

{% block content %}
    <h2>Create Post</h2>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Create Post</button>
    </form>
{% endblock %}

posts/templates/posts/create.html
{% extends 'accounts/base.html' %}
{% load static %}
{% block content %}
<br><br>
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <script src="https://kit.fontawesome.com/fc1e235b2e.js"></script>
  <link rel="stylesheet" href="{% static 'assets2/style.css' %}">
  <title>Instagram Login Form</title>
</head>

<body>
  <div id="wrapper">
    <div class="container">
      <div class="phone-app-ddemo"></div>
      <div class="form-data">
        <form action="" method="POST" enctype="multipart/form-data">
			{% csrf_token %}
          <div class="logo">
            <h3 style="padding: 20px; font-size: 20px;">Create New Post</h3>
          </div>
          {{form.image}} <br>
          {{form.caption.label_tag}} <br>
          {{form.caption}} <br>
          <button class="form-btn" type="submit">Post</button>
        </form>
      </div>
    </div>
    {% include 'partials/_footer.html' %}
  </div>
</body>
</html>
{% endblock content %}

posts/templates/posts/detail copy.html
{% extends 'accounts/base.html' %}
{% load comment_tags %}
{% block content %}
    <h2>{{ post.user.username }}'s Post</h2>
    <img src="{{ post.image.url }}" alt="{{ post.user.username }}'s post image" width="300">
    <p>{{ post.caption }}</p>
    {% if request.user.is_authenticated %}
        {% if request.user in post.likes.all %}
            <a href="{% url 'posts:like' post.pk %}">Unlike</a>
        {% else %}
            <a href="{% url 'posts:like' post.pk %}">Like</a>
        {% endif %}
    {% endif %}
    <p>{{ post.likes.count }} Likes</p>
    {% if request.user == post.user %}
        <a href="{% url 'posts:update' post.pk %}">Edit Post</a> |
        <a href="{% url 'posts:delete' post.pk %}">Delete Post</a>
    {% endif %}
    {% root_comments post as root_comments %}
    {% render_nested_comments root_comments %}
    <form method="post" action="{% url 'comments:create_comment' post_id=post.id %}">
        {% csrf_token %}
        {{ form.parent.as_hidden }}
        {{ form.text.label_tag }}<br>
        {{ form.text }}<br>
        <input type="submit" value="Add Comment">
    </form>
{% endblock %}

posts/templates/posts/detail.html
{% extends 'accounts/base.html' %}
{% load static %}
{% load comment_tags %}
{% block content %}
<head>
   <style>
      .date {
      font-size: 11px
      }
      .comment-text {
      font-size: 12px
      }
      .fs-12 {
      font-size: 12px
      }
      .shadow-none {
      box-shadow: none
      }
      .name {
      color: #007bff
      }
      .cursor:hover {
      color: blue
      }
      .cursor {
      cursor: pointer
      }
      .textarea {
      resize: none
      }
   </style>
</head>
<main class="main-container">
   <section class="content-container">
      <div class="contendt">
         <div class="posts">
            <article class="post">
               <div class="post__header">
                  <div class="post__profile">
                     <a href="{% url 'profiles:detail' post.user.pk %}" class="post__avatar">
                     <img src="{{ post.user.profile.profile_picture.url }}" alt="User Picture">
                     </a>
                     <a href="{% url 'profiles:detail' post.user.pk %}" class="post__user">@{{ post.user.username }}</a>
                  </div>
                  {% if request.user == post.user %}
                  <div class="dropdown">
                      <a class="btn btn-secondary dropdown-toggle bg-light" href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false" style="height:30px">
                          <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                          <circle cx="6.5" cy="11.5" r="1.5" fill="var(--text-dark)"/>
                          <circle cx="12" cy="11.5" r="1.5" fill="var(--text-dark)"/>
                          <circle cx="17.5" cy="11.5" r="1.5" fill="var(--text-dark)"/>
                          </svg>
                      </a>
                      <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                          <li><a class="dropdown-item" href="{% url 'posts:update' post.pk %}">Update Post</a></li>
                          <li><a class="dropdown-item list-group-item list-group-item-danger" href="{% url 'posts:delete' post.pk %}">Delete Post</a></li>
                      </ul>
                  </div>
                  {% endif %}
               </div>
               <div class="post__content">
                  <div class="post__medias">
                     <a href="{% url 'posts:detail' post.id %}"><img class="post__media" src="{{ post.image.url }}" alt="Post Content" style="width:1000%; object-fit: contain;"></a><!--                                <img class="post__media" src="{% static 'assets1/insta-clone.png' %}" alt="Post Content">--><!--                                <img class="post__media" src="{% static 'assets1/insta-clone.png' %}" alt="Post Content">-->
                  </div>
               </div>
               <div class="post__footer">
                  <div class="post__buttons">
                    {% if request.user in post.likes.all %}
                    <a href="{% url 'posts:like' post.pk %}" class="post__button">
                        <svg aria-label="Unlike" class="x1lliihq x1n2onr6" color="rgb(255, 48, 64)" fill="rgb(255, 48, 64)" height="24" role="img" viewBox="0 0 48 48" width="24"><title>Unlike</title>
                            <path d="M34.6 3.1c-4.5 0-7.9 1.8-10.6 5.6-2.7-3.7-6.1-5.5-10.6-5.5C6 3.1 0 9.6 0 17.6c0 7.3 5.4 12 10.6 16.5.6.5 1.3 1.1 1.9 1.7l2.3 2c4.4 3.9 6.6 5.9 7.6 6.5.5.3 1.1.5 1.6.5s1.1-.2 1.6-.5c1-.6 2.8-2.2 7.8-6.8l2-1.8c.7-.6 1.3-1.2 2-1.7C42.7 29.6 48 25 48 17.6c0-8-6-14.5-13.4-14.5z"></path>
                        </svg>
                     </a>
                    {% else %}
                    <a href="{% url 'posts:like' post.pk %}" class="post__button">
                        <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                           <path d="M11.4995 21.2609C11.1062 21.2609 10.7307 21.1362 10.4133 20.9001C8.2588 19.3012 3.10938 15.3239 1.81755 12.9143C0.127895 9.76543 1.14258 5.72131 4.07489 3.89968C5.02253 3.31177 6.09533 3 7.18601 3C8.81755 3 10.3508 3.66808 11.4995 4.85726C12.6483 3.66808 14.1815 3 15.8131 3C16.9038 3 17.9766 3.31177 18.9242 3.89968C21.8565 5.72131 22.8712 9.76543 21.186 12.9143C19.8942 15.3239 14.7448 19.3012 12.5902 20.9001C12.2684 21.1362 11.8929 21.2609 11.4995 21.2609ZM7.18601 4.33616C6.34565 4.33616 5.5187 4.57667 4.78562 5.03096C2.43888 6.49183 1.63428 9.74316 2.99763 12.2819C4.19558 14.5177 9.58639 18.6242 11.209 19.8267C11.3789 19.9514 11.6158 19.9514 11.7856 19.8267C13.4082 18.6197 18.799 14.5133 19.997 12.2819C21.3603 9.74316 20.5557 6.48738 18.209 5.03096C17.4804 4.57667 16.6534 4.33616 15.8131 4.33616C14.3425 4.33616 12.9657 5.04878 12.0359 6.28696L11.4995 7.00848L10.9631 6.28696C10.0334 5.04878 8.6611 4.33616 7.18601 4.33616Z" fill="var(--text-dark)" stroke="var(--text-dark)" stroke-width="0.6"/>
                        </svg>
                     </a>
                    {% endif %}
                     <button class="post__button">
                        <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                           <path fill-rule="evenodd" clip-rule="evenodd" d="M21.2959 20.8165L20.2351 16.8602C20.1743 16.6385 20.2047 16.3994 20.309 16.1907C21.2351 14.3342 21.5438 12.117 20.9742 9.80402C20.2003 6.67374 17.757 4.16081 14.6354 3.33042C13.7833 3.10869 12.9442 3 12.1312 3C6.29665 3 1.74035 8.47365 3.31418 14.5647C4.04458 17.3819 7.05314 20.2992 9.88344 20.9861C10.6486 21.173 11.4008 21.26 12.1312 21.26C13.7006 21.26 15.1701 20.8557 16.4614 20.1601C16.6049 20.0818 16.7657 20.0383 16.9222 20.0383C17.0005 20.0383 17.0787 20.047 17.157 20.0688L21.009 21.0991C21.0307 21.1035 21.0525 21.1078 21.0699 21.1078C21.2177 21.1078 21.3351 20.9687 21.2959 20.8165ZM19.0178 17.1863L19.6178 19.4253L17.4831 18.8558C17.3005 18.8079 17.1135 18.7819 16.9222 18.7819C16.557 18.7819 16.1875 18.8775 15.8571 19.0558C14.6963 19.6818 13.4441 19.9992 12.1312 19.9992C11.4834 19.9992 10.8269 19.9166 10.1791 19.7601C7.78354 19.1775 5.14453 16.6037 4.53586 14.2473C3.90111 11.7865 4.40109 9.26057 5.90536 7.31719C7.40964 5.3738 9.6791 4.26081 12.1312 4.26081C12.8529 4.26081 13.5876 4.35646 14.3137 4.5521C16.9961 5.26511 19.0786 7.39544 19.7525 10.1084C20.2264 12.0213 20.0308 13.9299 19.183 15.6298C18.9395 16.1168 18.8787 16.6689 19.0178 17.1863Z" fill="var(--text-dark)" stroke="var(--text-dark)" stroke-width="0.7"/>
                        </svg>
                     </button>
                     <button class="post__button">
                        <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                           <path fill-rule="evenodd" clip-rule="evenodd" d="M22.8555 3.44542C22.6978 3.16703 22.3962 3 22.0714 3L2.91369 3.01392C2.52859 3.01392 2.19453 3.25055 2.05997 3.60781C1.96254 3.86764 1.98574 4.14603 2.11565 4.37338C2.16669 4.45689 2.23165 4.53577 2.31052 4.60537L9.69243 10.9712L11.4927 20.5338C11.5623 20.9096 11.8499 21.188 12.2304 21.2483C12.6062 21.3086 12.9774 21.1323 13.1723 20.8029L22.8509 4.35018C23.0179 4.06715 23.0179 3.72381 22.8555 3.44542ZM4.21748 4.39194H19.8164L10.4255 9.75089L4.21748 4.39194ZM12.6248 18.9841L11.1122 10.948L20.5171 5.58436L12.6248 18.9841Z" fill="var(--text-dark)" stroke="var(--text-dark)" stroke-width="0.3"/>
                        </svg>
                     </button>
                     <div class="post__indicators"></div>
                     <button class="post__button post__button--align-right">
                        <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                           <path d="M19.875 2H4.125C3.50625 2 3 2.44939 3 3.00481V22.4648C3 23.0202 3.36563 23.1616 3.82125 22.7728L11.5444 16.1986C11.7244 16.0471 12.0225 16.0471 12.2025 16.1936L20.1731 22.7879C20.6287 23.1666 21 23.0202 21 22.4648V3.00481C21 2.44939 20.4994 2 19.875 2ZM19.3125 20.0209L13.3444 15.0827C12.9281 14.7394 12.405 14.5677 11.8763 14.5677C11.3363 14.5677 10.8019 14.7444 10.3856 15.0979L4.6875 19.9502V3.51479H19.3125V20.0209Z" fill="var(--text-dark)" stroke="var(--text-dark)" stroke-width="0.7"/>
                        </svg>
                     </button>
                  </div>
                  <div class="post__infos">
                     <div class="post__likes">
                        <a href="#" class="post__likes-avatar">
                           <!--                                        <img src="assets1/default-user.png" alt="User Picture">-->
                        </a>
                        <span>{{post.likes.count}} <a class="post__name--underline" href="#">likes</a> <a href="#"></a></span>
                     </div>
                     <div class="post__description">
                        <span>
                        <a class="post__name--underline" href="#"><b>@{{post.user.username}}</b></a>
                        {{post.caption}}
                        </span>
                     </div>
                     <!-- <p style="font-size: 13px;">{% for tag in post.tags.all %}
                        <a href="{{ tag.get_absolute_url }}" style="text-decoration: none;">
                        #{{ tag }}
                        </a>
                        {% endfor %}
                     </p> -->
                     <span class="post__date-time">{{post.created_at}}</span>
                     <div class="container mt-1">
                        <div class="d-flex justify-content-right row">
                           <div class="col-md-8 col-lg-8">
                              <div class="d-flex flex-column comment-section">
                                {% root_comments post as root_comments %}
                                {% render_nested_comments root_comments %}
                                 <form method="post" action="{% url 'comments:create_comment' post_id=post.id %}">
                                    {% csrf_token %}
                                    {{ form.as_p }}
                                    <div class="bg-light p-2 mt-5">
                                       <div class="d-flex flex-row align-items-start"><img class="rounded-circle" src="{{request.user.profile.profile_picture.url}}" width="30" height="30">{{form.body}}</div>
                                       <div class="mt-2 text-right">
                                           <textarea name="text" required id="id_text" class="form-control shadow-none" placeholder="Add a comment..." rows="1"></textarea>
                                           <button class="btn btn-primary btn-sm shadow-none mt-3" type="submit">Post comment</button>
                                    </div>
                                    </div>
                                 </form>
                              </div>
                           </div>
                        </div>
                     </div>
                  </div>
               </div>
            </article>
         </div>
      </div>
   </section>
</main>
{% endblock content %}

posts/templates/posts/post_feed.html
{% extends 'accounts/base.html' %}

{% block content %}
  <h2>Post Feed</h2>

  {% for post in post_items %}
    <div>
      <h3>{{ post.user.username }}</h3>
      <img src="{{ post.image.url }}" alt="{{ post.user.username }}'s post image" width="150">
      <p>{{ post.caption }}</p>
      <small>{{ post.created_at }}</small>
    </div>
  {% empty %}
    <p>No posts yet.</p>
  {% endfor %}

  {% if users_paginator %}
    <h3>Users</h3>
    {% for user in users_paginator %}
      <div>
        <h4>{{ user.username }}</h4>
      </div>
    {% endfor %}
  {% endif %}
{% endblock %}

posts/templates/posts/update copy.html
{% extends 'accounts/base.html' %}

{% block content %}
    <h2>Update Post</h2>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Update Post</button>
    </form>
{% endblock %}

posts/templates/posts/update.html
{% extends 'accounts/base.html' %}
{% load static %}
{% block content %}
<br><br>
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <script src="https://kit.fontawesome.com/fc1e235b2e.js"></script>
  <link rel="stylesheet" href="{% static 'assets2/style.css' %}">
  <title>Instagram Login Form</title>
</head>

<body>
  <div id="wrapper">
    <div class="container">
      <div class="phone-app-ddemo"></div>
      <div class="form-data">
        <form action="" method="POST" enctype="multipart/form-data">
			{% csrf_token %}
          <div class="logo">
            <h3 style="padding: 20px; font-size: 20px;">Edit Post</h3>
          </div>
          {{form.image}} <br>
          {{form.caption.label_tag}} <br>
          {{form.caption}} <br>
          <button class="form-btn" type="submit">Post</button>
        </form>
      </div>
    </div>
    {% include 'partials/_footer.html' %}
  </div>
</body>
</html>
{% endblock content %}